// This file is automatically generated. Keep the production fallbacks in place:
// Lovable's published build may not always inject VITE_* variables into lazy chunks.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const FALLBACK_SUPABASE_URL = "https://cyymcdqkpvcvwjoqxbco.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eW1jZHFrcHZjdndqb3F4YmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3OTM0OTAsImV4cCI6MjA5MjM2OTQ5MH0.9WavmFju3ASsXZqFDtMcekaBdiyW3shHf2DspFMfk5U";

const configuredUrl = import.meta.env.VITE_SUPABASE_URL?.trim();
const configuredKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

const SUPABASE_URL = configuredUrl || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = configuredKey || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
